# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69292906dc148bbc64821638777c4ac8bbf63ffdb277ce496d71ebe75a755966a50a1656564d96df86f8e08a5e6515a10abbc1395451f85e22b811fdd415e2a9

test:
  secret_key_base: fc685b5942e8f8e5bc3fb6d49db5294d302ad2494982a69943d99d92bea1c016d51dd3a2eca3420aa52773c9c85c577e5ac48421903521e135d7f757f2e45da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
